### ISSUE TITLE
Implement cache in a way that it is retained once the container is down

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/grp-cantaloupe-v2#16]
Hi @fkraeutli 

Last Monday, we discussed the configuration of the cache and you proposed to map the cache directory to the disk, so that it is retained in case the container goes down or is being rebuilt. I played around with the location of the cache dir  and have successfully added this to `docker-compose.yml`

```
services:
    cantaloupe:
        build: .
        container_name: ${PROJECT_NAME}_cantaloupe
        image: swissartresearx/cantaloupe:5.0
        restart: always
        volumes:
            - ./cache:/cache
            - ./config:/config
            - ./images:/images
```

This above works. 

However, according to `cantaloupe.properties`the default location of the cache seems to be `# FilesystemCache.pathname = /var/cache/cantaloupe`. 

Thus,  I am wondering where in the container the cache dir should sit within the container. 

Is the following the better option?  

```
services:
    cantaloupe:
        build: .
        container_name: ${PROJECT_NAME}_cantaloupe
        image: swissartresearx/cantaloupe:5.0
        restart: always
        volumes:
            - /var/cache/cantaloupe:/cache
            - ./config:/config
            - ./images:/images
```

Any suggestions for best practice?
